version: "3.4"
services:
  db:
    image: docker-to-aws-with-dotnet-mysql-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_to_aws_with_dotnet
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  docker-to-aws-with-dotnet:
    image: docker-to-aws-with-dotnet
    restart: always
    build:
      context: .
      dockerfile: DockerToAWSWithDotNet/Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "5000:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge
    